"""
Corrected alamarBlue kinetics for the AMMPER-2 gamma radiation mode.

The submitted supplement reported that the alamarBlue model "failed to
recapitulate the experimental data" under gamma radiation (Fig. S9) and
attributed the failure to the model's binary health-state assumption. That
diagnosis was wrong. The gamma analysis script carried the same growth-curve
ordering bug as the proton scripts, so the ODE was driven by a population
trajectory running backwards in time, and no choice of kinetic constants could
have fitted the data.

-------------------------------------------------------------------------------
THE BUG, IN THE GAMMA CODE SPECIFICALLY
-------------------------------------------------------------------------------

analysis/gamma/aBFinalplotsGAMMA.py builds the two population curves like this:

    Growth_curve  = Healthy['Generation'].value_counts()      # healthy
    Growth_curve2 = Unhealthy['Generation'].value_counts()    # damaged
    Growth_curve  = np.array(Growth_curve)                    # index discarded
    ...
    for i in Growth_curve2.index:                             # index USED
        g.at[int(i), 'ncelldamaged'] = Growth_curve2[i]

The damaged curve is put back onto the generation index correctly. The healthy
curve is not: value_counts() sorts by frequency descending, which for a
monotonically growing population is descending generation order, and np.array()
throws away the index that would have revealed it. On the archived 2.5 Gy
wild-type output the healthy curve the ODE actually received was

    [2763 2757 2284 1493 824 446 246 137 75 40 21 12 6 4 2 1]

against the true

    [1 2 4 6 12 21 40 75 137 246 446 824 1493 2284 2763 2757]

so the model was told the population starts saturated and dies away. The
predicted blue curve then falls from the first timestep regardless of dose, which
is the shape in the submitted figure. The healthy curve is the term that carries
essentially all of the metabolic capacity -- damaged cells enter weighted by
k = 0.034 -- so reversing it dominates the prediction.

-------------------------------------------------------------------------------
WHAT THIS MODULE DOES DIFFERENTLY, AND WHY
-------------------------------------------------------------------------------

1. Ordering fixed, by reusing the proton module's _counts_by_generation.

2. THE SAME KINETICS AS THE PROTON FIT, NOT A NEW SCHEME. The legacy gamma
   script used a structurally different and simpler model from the one now used
   for protons: two Michaelis-Menten steps (V1_max, V2_max, K1_M, K2_M) running
   blue -> pink -> colorless irreversibly, against the three-species reversible
   blue -> pink <-> colorless chain of the proton model. Here the gamma
   predictions are generated by the proton model, because the redox chemistry of
   alamarBlue is a property of the dye and cannot depend on which radiation
   quality damaged the cells. That makes the gamma comparison a genuine test
   rather than a second fitting exercise: the dye constants are transferred from
   the proton fit unchanged and only the inoculum offset g0, which is a property
   of how densely the plate was seeded, is refit. See fit_gamma_ab_model.py,
   which also reports what a full refit of the kinetics to the gamma data buys,
   for comparison.

3. Generation time 205.62 min rather than 198 min, carried over from the legacy
   gamma script: the gamma experiment ran for a different total duration than the
   150 MeV proton experiment over the same 15 simulated generations.

4. The 0 Gy control is taken from the proton simulations. GammaRadGen refuses a
   zero dose, and rightly: at 0 Gy there are no deposition events, so the gamma
   and proton branches of AMMPERBulk both reduce to Brownian motion plus
   replication in a 64-micron cube for 15 generations. The 0 Gy simulation is the
   same object either way, and re-running it under a gamma label would present
   one computation twice.

-------------------------------------------------------------------------------
THE SECOND DEFECT: THE HIT RATE
-------------------------------------------------------------------------------

Fixing the ordering improves the gamma fit but does not rescue it, and running
the dose series for the first time shows why. GammaRadGen converts dose to event
count with n_Hits = dose * k, k = 100, under a source comment reading "k = 100 is
arbitrary for now, need physical parameters to calculate the number of events in
an area 64 x 64 micrometers" -- and, on the line below, "scan k = [1,2,3,4,5] see
which one matches expected population ratio". The three archived gamma folders
(WT_25, WT_250, WT_25k50) are that unfinished scan: the same 2.5 Gy dose at
k = 100, 1000 and 50. The calibration was intended and never done.

At the published rate the simulated wild-type population retains 1.3% of the
unirradiated healthy count at 20 Gy, where the measured growth channel retains
76%. Since the population trajectory is this model's only input, no dye chemistry
could reconcile that. Calibrating k against the OD690 growth channel -- cell
density, not the aB series predicted here -- gives k = 1.85, so the published
value is 54x too many events per Gray. See calibrate_gamma_hit_rate.py.

Because n_Hits depends on dose and k only through their product, recalibrating k
is exactly a rescaling of the dose axis: the calibrated conditions are the
UNMODIFIED simulator run at the equivalent dose, dose * k / 100. Nothing in
src/ is patched. Both configurations are analyzed here, selected by
USE_CALIBRATED_HIT_RATE and by the ``calibrated`` argument of conditions() and
the loaders, because the published-rate runs are the evidence for what went
wrong.

-------------------------------------------------------------------------------
USAGE
-------------------------------------------------------------------------------

    import ammper_ab_model_gamma as G

    curves = G.load_growth_curves('WT')        # {condition key: GrowthCurve}
    exp    = G.load_experimental('WT')         # {condition key: Measurement}
    pred   = G.predict(curves['gWT_2.5'], G.SHARED_PARAMS, g0=G.WT_G0)
    mae    = M.mean_absolute_error(pred, exp['gWT_2.5'])
"""

import functools
import json
import os
import sys
from collections import namedtuple

import numpy as np
import pandas as pd

import ammper_ab_model_fixed as M
import extract_gamma_experimental

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))
import ammper_paths as P  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

#: Simulated generations, as in the proton work (AMMPERBulk_GAMMAfinal sets 15).
NGEN = M.NGEN

#: Hours of each curve compared, matching the proton analysis.
TRUNCATE_HOURS = M.TRUNCATE_HOURS

#: Minutes per generation for the gamma experiment. From the legacy gamma script,
#: where the constant is commented "198 min for ion conversion data, 205.62 for
#: gamma radiation": the two experiments ran for different total durations over
#: the same number of simulated generations. Like the proton value this is a
#: hyperparameter of the comparison, not a fitted quantity, and it trades off
#: against g0.
GENERATION_MINUTES = 205.62

#: Hit rate in GammaRadGen as published: deposition events per Gy per x-plane.
#: Retained because the uncalibrated conditions are still analyzed, as the
#: evidence that this value is what broke the gamma predictions.
PUBLISHED_HIT_RATE = 100

#: Whether the analysis uses the calibrated hit rate. The published value puts
#: the simulated population past extinction before the measured dose range
#: begins -- 1.3% of the unirradiated healthy count at 20 Gy, against 76% of the
#: control measured -- so at the published rate the growth curve reaching the aB
#: model carries no recoverable dose information above about 10 Gy. See
#: calibrate_gamma_hit_rate.py, which fits the rate to the OD690 growth channel
#: (cell density) rather than to the aB series this model predicts.
USE_CALIBRATED_HIT_RATE = True

GammaCondition = namedtuple('GammaCondition',
                            'key strain dose_gy sim_folder csv_stem is_proton_sim')


def _sim_folder(strain, dose):
    """Simulation folder for an uncalibrated gamma condition.

    Kept in step with run_gamma_simulations.condition_folder by construction: both
    build the name from the same pieces, and load_growth_curves fails loudly if a
    folder is missing rather than silently dropping the condition.
    """
    tag = f'{dose:g}'.replace('.', '') if dose < 10 else f'{dose:g}'
    return os.path.join('revision2026', f'gamma_{strain}_Basic_{tag}')


def _calibrated_sim_folder(strain, dose):
    """Simulation folder for a calibrated-dose run, keyed by the nominal dose.

    Delegates to calibrate_gamma_hit_rate so the naming rule lives in exactly one
    place. These runs are the unmodified simulator invoked at the *equivalent*
    dose: because GammaRadGen depends on dose and the hit rate only through their
    product, running dose * k_calibrated / 100 at the published rate is
    identically the same computation as running the nominal dose at the
    calibrated rate. Nothing in the simulator is patched.
    """
    import calibrate_gamma_hit_rate as C
    return C.calibrated_folder(strain, dose)


#: Gamma doses analyzed. The experiment read out fifteen doses per strain; these
#: five match the proton series, so the same dose can be compared across
#: radiation qualities. See run_gamma_simulations.DOSES for the full simulated
#: set, which spans 0.01-30 Gy and is what the hit-rate calibration is built on.
DOSES = [0.0, 2.5, 5.0, 10.0, 20.0, 30.0]


def _condition(strain, dose, calibrated=None):
    # The CSV name comes from the extractor's own naming rule rather than being
    # rebuilt here, so the two cannot drift: writing "2.5 Gy" as 25Gy or as
    # 2.5Gy is exactly the kind of duplicated convention that produced the
    # 5/10 Gy label swap in the submitted figure.
    tag = extract_gamma_experimental.dose_tag(dose)
    calibrated = USE_CALIBRATED_HIT_RATE if calibrated is None else calibrated
    if dose == 0:
        # 0 Gy: the proton simulation, for the reason given in the module
        # docstring. Its folder lives under results/bulk_aB/, not bulk_gamma/.
        # The hit rate is irrelevant at zero dose -- no events are generated
        # either way -- so the control is shared by both configurations.
        proton = {'WT': 'WT_Basic_0', 'rad51': 'rad51_Basic_0'}[strain]
        return GammaCondition(f'g{strain}_0', strain, 0.0, proton,
                              f'AlamarblueGamma{strain}0Gy.csv', True)
    folder = (_calibrated_sim_folder(strain, dose) if calibrated
              else _sim_folder(strain, dose))
    return GammaCondition(f'g{strain}_{dose:g}', strain, dose, folder,
                          f'AlamarblueGamma{strain}{tag}.csv', False)


CONDITIONS = [_condition(strain, dose)
              for strain in ('WT', 'rad51') for dose in DOSES]


def conditions(strain=None, calibrated=None):
    """Gamma conditions for one strain ('WT' or 'rad51'), ascending in dose.

    ``calibrated`` selects which simulation set the conditions point at; it
    defaults to USE_CALIBRATED_HIT_RATE. The condition keys are the same either
    way, so a caller can compare the two configurations dose by dose.
    """
    out = [_condition(s, d, calibrated=calibrated)
           for s in ('WT', 'rad51') for d in DOSES
           if strain is None or s == strain]
    return sorted(out, key=lambda c: c.dose_gy)


# ---------------------------------------------------------------------------
# Simulation output -> growth curves
# ---------------------------------------------------------------------------

#: Output filename written by each simulator branch. The gamma branch of
#: AMMPERBulk_GAMMAfinal.py writes Gamma.txt; the proton branch writes
#: "<dose>Gy.txt", which is why the 0 Gy control is matched by suffix.
GAMMA_DATA_FILE = 'Gamma.txt'


def _run_frames(cond):
    """Per-replicate simulation output frames for a condition."""
    root = (P.bulk_aB(cond.sim_folder) if cond.is_proton_sim
            else P.bulk_gamma(cond.sim_folder))
    frames = []
    for directory, _dirs, files in os.walk(root):
        wanted = [f for f in files
                  if (f.endswith('Gy.txt') if cond.is_proton_sim
                      else f == GAMMA_DATA_FILE)]
        if not wanted:
            continue
        frames.append(pd.read_csv(os.path.join(directory, sorted(wanted)[0]),
                                  names=['Generation', 'x', 'y', 'z', 'Health']))
    if not frames:
        raise FileNotFoundError(
            f'no simulation output for {cond.key} under {root}. '
            f'Run run_gamma_simulations.py first.')
    return frames


def load_growth_curves_per_run(strain=None, calibrated=None):
    """One GrowthCurve per replicate: ``{condition key: [GrowthCurve]}``.

    Correctly ordered by generation, which is the fix for the bug this module
    exists to correct.
    """
    out = {}
    for cond in conditions(strain, calibrated):
        out[cond.key] = [
            M.GrowthCurve(healthy=M._counts_by_generation(frame, 1),
                          unhealthy=M._counts_by_generation(frame, 2),
                          n_runs=1)
            for frame in _run_frames(cond)]
    return out


def load_growth_curves(strain=None, calibrated=None):
    """Replicate-averaged growth curves: ``{condition key: GrowthCurve}``."""
    per_run = load_growth_curves_per_run(strain, calibrated)
    return {key: M.GrowthCurve(
                healthy=np.mean(np.stack([r.healthy for r in runs]), axis=0),
                unhealthy=np.mean(np.stack([r.unhealthy for r in runs]), axis=0),
                n_runs=len(runs))
            for key, runs in per_run.items()}


def load_buggy_growth_curves(strain=None):
    """The growth curves as the published gamma code fed them to the ODE.

    Reproduces value_counts() ordering exactly: the healthy curve sorted by
    descending count with its index discarded, the damaged curve correctly
    reindexed. Used only to show the size of the correction; nothing reported as
    a result goes through this.

    Always reads the published-hit-rate runs, whatever USE_CALIBRATED_HIT_RATE
    says: this function exists to reproduce the submitted figure, and the
    submitted figure was made at k = 100.
    """
    out = {}
    for cond in conditions(strain, calibrated=False):
        curves = []
        for frame in _run_frames(cond):
            healthy = frame[frame['Health'] == 1]['Generation'].value_counts()
            padded = np.zeros(NGEN + 1)
            values = healthy.to_numpy(dtype=float)
            padded[:len(values)] = values
            curves.append(M.GrowthCurve(
                healthy=padded,
                unhealthy=M._counts_by_generation(frame, 2),
                n_runs=1))
        out[cond.key] = curves
    return out


# ---------------------------------------------------------------------------
# Plate reader -> experimental concentrations
# ---------------------------------------------------------------------------

def load_experimental(strain=None, with_error=False, calibrated=None):
    """Gamma alamarBlue measurements, in the same units as the proton series.

    Reads the CSVs written by extract_gamma_experimental.py and applies the
    published normalization unchanged, including its two different denominators
    (see ammper_ab_model_fixed.load_experimental for why that is deliberate and
    must not be "simplified"). The experimental values themselves are exactly
    those in the source workbooks. The ``calibrated`` argument is accepted only so
    that this loader can be called with the same signature as the growth-curve
    loaders; it cannot change what is returned, because recalibrating the hit rate
    is a statement about the simulator and the measurements are untouched.
    """
    out = {}
    for cond in conditions(strain, calibrated):
        frame = pd.read_csv(P.ab_gamma_experimental(cond.csv_stem),
                            names=M.CSV_COLUMNS).head(TRUNCATE_HOURS)
        blue, pink, time = M._absorbance_to_concentrations(frame)
        blue = blue / (blue[0] + pink[0])
        pink = pink / (blue[0] + pink[0])   # published convention, verbatim
        measurement = M.Measurement(time=time, blue=blue, pink=pink)
        if not with_error:
            out[cond.key] = measurement
            continue
        std = pd.read_csv(
            P.ab_gamma_experimental(cond.csv_stem.replace('.csv', 'STD.csv')),
            names=M.CSV_COLUMNS).head(TRUNCATE_HOURS)
        bands = {}
        for sign, name in ((+1, 'upper'), (-1, 'lower')):
            shifted = frame.copy()
            for column in ('A570', 'A600', 'A690', 'A750'):
                shifted[column] = (frame[column].to_numpy()
                                   + sign * std[column].to_numpy())
            b, p, _ = M._absorbance_to_concentrations(shifted)
            b = b / (b[0] + p[0])
            p = p / (b[0] + p[0])
            bands[name] = (b, p)
        out[cond.key] = (measurement, bands)
    return out


# ---------------------------------------------------------------------------
# Prediction
# ---------------------------------------------------------------------------

def predict(growth_curve, params, g0, **kwargs):
    """Proton kinetics driven by a gamma growth curve, on the gamma clock."""
    kwargs.setdefault('generation_minutes', GENERATION_MINUTES)
    kwargs.setdefault('hours', TRUNCATE_HOURS)
    return M.predict(growth_curve, params, g0, **kwargs)


mean_absolute_error = M.mean_absolute_error

#: Dye constants, transferred unchanged from the proton fit. Not refit for gamma:
#: the point of the gamma comparison is whether one dye chemistry serves both
#: radiation qualities.
SHARED_PARAMS = M.SHARED_PARAMS


@functools.lru_cache(maxsize=1)
def _fitted():
    """Offsets fit by fit_gamma_ab_model.py, or None if it has not been run."""
    path = os.path.join(HERE, 'fitted_parameters_gamma.json')
    if not os.path.exists(path):
        return None
    with open(path) as handle:
        return json.load(handle)


def params_for(strain):
    """``(params, g0)`` for a gamma strain.

    Raises if the gamma offsets have not been fit yet, rather than silently
    falling back on the proton offsets: the gamma experiment was seeded and timed
    separately, so its g0 is a different quantity even though the kinetics are
    shared.
    """
    fit = _fitted()
    if fit is None:
        raise FileNotFoundError(
            'fitted_parameters_gamma.json not found -- run fit_gamma_ab_model.py')
    return tuple(fit['transferred']['params']), fit['transferred']['g0'][strain]
